### ISSUE TITLE
Minimal privileges needed to start dind

### ISSUE THREAD

**Issue by anomalizer** [jpetazzo/dind#60] opened 2015-02-27 10:35 UTC
Docker provides fine grained capabilities that can be enabled when launching the container. The current recommended way to launch the outer container within which _dind_ executes is by passing the **--privileged** flag.

The recommended way should be to run it using **--cap-add** by providing a minimal set of permissions to the outer container instance such that a networked _dind_ instance can be started. Volume addition should also require additional flags. Extra capabilities if any need to be provided based on the needs of the specific app that we intend to run as _dind_

**Comment by jpetazzo** [comment] 2015-02-27 15:54
This is a duplicate of #43 :-)

TL,DR: I agree that this would be a nice item for the roadmap, but I would rather have a PR than a Nth open issue without direct actionable item.

Thank you!

**Closed by jpetazzo** 2015-02-27 15:54 UTC
